### ISSUE TITLE
Creation Date: Put in wrong place

### ISSUE THREAD

**Issue by nihaals** [Natsulus/BD-Repo#1]
When clicking on a mention in chat, the `Created on` is place above the name

![image](https://user-images.githubusercontent.com/18350092/29751518-7130402c-8b46-11e7-8967-ccd1e68bfdc3.png)

**Comment by Natsulus** [comment]
Rather than changing class name this time, Discord changed DOM element positions which is what caused this. Fixed with commit bb20affd03523efc01462882059136d79fcc3e23.
