### ISSUE TITLE
Creation date not working anymore

### ISSUE THREAD

**Issue by mortebrume** [Natsulus/BD-Repo#2]
I do not see anything, now.

Idk why.

Restarted discord twice, re-dl the plugin => Nothing.

[https://i.imgur.com/1Xf99QX.png](url)

**Comment by Natsulus** [comment]
Discord's latest update included them updating to React 16. This update in React version changes the structure of the React data that the plugin used. I've just now fixed it in v1.1.5 (94db4d7).
