### ISSUE TITLE
If this plugin is not working for you on the latest update read this...

### ISSUE THREAD

**Issue by BannerBomb** [Natsulus/BD-Repo#6]
Since this plugin was not working on the latest discord update I decided to edit the plugin myself and fix it, all you need to do is 2 simple steps which are listed below.

Open the CreationDate.plugin.js file and goto line 37 and change
`const activity = $(ev.addedNodes[0].childNodes[0]).find(".headerActivityText-3qBQRo");`
to
`const activity = $(ev.addedNodes[0].childNodes[0]).find(".headerText-3tKBWq");`
@Natsulus

**Comment by BannerBomb** [comment]
@Natsulus bump

**Comment by User486375** [comment]
@BannerBomb Thanks that worked like a charm! Just wondering would there also be an easy fix for this? https://github.com/XFoxPrower/Quick-Open-Link (it doesn't allow BD to even load).

**Comment by just-Addict** [comment]
@BannerBomb 
LOL, With the very latest Discord update of a few days ago. the plugin don't even get that far it already dies on 
```
    observer(ev) {
		if (ev.addedNodes.length > 0 && ev.addedNodes[0].className && typeof ev.addedNodes[0].className === "string" && ev.addedNodes[0].className.includes("popout") 
			&& ev.addedNodes[0].childNodes.length > 0 && ev.addedNodes[0].childNodes[0].className.includes("userPopout")) {
```
with `Uncaught TypeError: Cannot read property 'includes' of undefined`

sigh...

**Comment by BannerBomb** [comment]
Sorry for my late replies I had to send out my computer for repairs again and my school computer crashed too but I'll look at the plugin is it this same plugin that does on the latest update?

**Comment by BannerBomb** [comment]
Sorry for my late replies I had to send out my computer for repairs again and my school computer crashed too but I'll look at the plugin As soon as I can.

**Update1**
the ``includes undefined`` error sounds like it means that the classnames either ``userPopout`` and/or ``popout`` don't exist anymore so it's saying that they are undefined in the script because they cannot be found so within the ``className.includes("popout")`` and ``.className.includes("userPopout")`` lines where it says ``userPopout`` and ``popout`` needs to be changed to what it is now, I'll check the new values and let u know the new values.

**Update2**
Try changing ``.className.includes("userPopout")`` to ``.className.includes("userPopout-4pfA0d")``

Cause as I see in discord script it shows ``popouts`` and ``userPopout-4pfA0d`` **NOT** ``userPopout`` anymore let me know if this works as I cannot test it atm without my computer. If this does not work then I can try changing the script a tad.
@User486375

**Comment by BannerBomb** [comment]
Sorry for 2 comments but i can't edit comments on my iPod anyway what plugin are u having this issue with ? ``with Uncaught TypeError: Cannot read property 'includes' of undefined``

**Comment by BannerBomb** [comment]
Ok I remembered with the ``includes undefined`` error that means that the classnames ``userPopout`` and ``popout`` don't exist anymore so it's saying that they are undefined in the script because they cannot be found so within the ``className.includes("popout")`` and ``.className.includes("userPopout")`` lines where it says ``userPopout'' and ``popout`` needs to be changed to what it is now, I'll check the new values and let u know the new values.

**Comment by BannerBomb** [comment]
Try changing ``.className.includes("userPopout")`` to ``userPopout-4pfA0d``

Cause as I see in discord script it shows ``popouts`` and ``userPopout-4pfA0d`` **NOT** ``userPopout`` anymore

**Comment by User486375** [comment]
@BannerBomb There isn't a `.className.includes("userPopout")` in the code from what I can see? Could it be something else? And take as long as you want, I'm in no rush!

**Comment by BannerBomb** [comment]
@User486375 its right beneath the observer function

```javascript
observer(ev) {
		if (ev.addedNodes.length > 0 && ev.addedNodes[0].className && typeof ev.addedNodes[0].className === "string" && ev.addedNodes[0].className.includes("popout") 
&& ev.addedNodes[0].childNodes.length > 0 && ev.addedNodes[0].childNodes[0].className.includes("userPopout")) {
```
**.className.includes("userPopout")** is at the very last line of the snippet above

**Comment by User486375** [comment]
@BannerBomb Sorry, I think you're looking at the wrong plugin? Sorry if I confused you by replying to this issue, but `CreationDate.plugin.js` works fine for me with your change. It's `Quick Open Link.plugin.js` that I linked to in my first comment that I have an issue with discord not loading.

**Comment by BannerBomb** [comment]
oh ok, I had a email from this issue that said ``LOL, With the latest discord update of a few days ago . the plugin dont even get that far it already dies on. [Script from my last comment above] sigh...`` and I pressed view on githuub and it brung me here, only me and you are the participating people here, so I thought u sent it. ok sorry let me see what i can do with the other plugin.

**Comment by BannerBomb** [comment]
@User486375 can u open discord with the ``Quick Open Link`` plugin turned on, and while in the discord app press ``Ctrl``+``Shift``+``I`` then pres the ``Console`` tab in the menu that opens and send an image of the errors(red text) itll look something like in the photo 
<img width="741" alt="console-panel" src="https://user-images.githubusercontent.com/11788894/34315307-f5f11334-e74b-11e7-97d1-8a8212a21673.png">

this way i can see what discord is saying about the plugin while its trying to load it.

**Comment by User486375** [comment]
@BannerBomb 
![discord_2017-12-23_00-31-01](https://user-images.githubusercontent.com/30012923/34315558-28cb3852-e779-11e7-95eb-b8dc58ec4c41.png)
The rest of the errors are there with or without the plugin.

**Comment by BannerBomb** [comment]
ok that helps narrow it down, all I need is the ones talking about the plugin.

**Comment by BannerBomb** [comment]
@User486375 try this I changed a few things in the script let me know if it dont work and with the errors please. [Download Plugin](https://raw.githubusercontent.com/BannerBomb/BetterDiscordAddons/master/Plugins/Quick%20Open%20Link/Quick%20Open%20Link.plugin.js)

**Comment by User486375** [comment]
@BannerBomb It seems to be giving me the exact same error
![discord_2017-12-23_02-43-54](https://user-images.githubusercontent.com/30012923/34316348-2e04c272-e78b-11e7-8ee4-b9de8e3cd0a2.png)

**Comment by BannerBomb** [comment]
Ok i know it's something to do with the const variable and the event listener

**Comment by BannerBomb** [comment]
It's either because the variable is a const or because the element Ids don't exist yet while discord is being loaded

**Comment by yorik100** [comment]
Now it shows twice the date

**Comment by BannerBomb** [comment]
sorry i should be getting my pc back within a few days now, but also BetterDiscord has changed if your BD isnt working in the latest update you have to install the alternative BD from [https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82](Here) and make sure to check the checkboxes shown in the image included when installing
![unnamed](https://user-images.githubusercontent.com/11788894/34749868-e3425d90-f571-11e7-8d50-1f1180921152.png)

**Comment by User486375** [comment]
@BannerBomb  Hey, sorry for the slow reply. Seems someone else found the problem and fixed it [here](https://github.com/XFoxPrower/Quick-Open-Link/issues/1).

**Comment by yorik100** [comment]
TypeError: Cannot read property 'childNodes' of undefined
    at CreationDate.observer (<anonymous>:39:20)
    at PluginModule.rawObserver (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/7fdd27e55e84f1b380cecfc8e87367b24abb43e3/js/main.min.js:52:19573)
    at https://cdn.rawgit.com/rauenzi/BetterDiscordApp/7fdd27e55e84f1b380cecfc8e87367b24abb43e3/js/main.min.js:1:8708
    at Array.forEach (native)
    at MutationObserver.<anonymous> (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/7fdd27e55e84f1b380cecfc8e87367b24abb43e3/js/main.min.js:1:8638)
e.(anonymous function) @ f36f220….js:25
f36f220
